name: Instabuild
version: '1.2.2'
main: me.lukiiy.instabuild.Instabuild
author: Lukiiy
description: A creative mode, but for b1.7.3
commands:
  instabuild:
    permission: instabuild.use
    usage: "/instabuild"
    aliases: [ "ib" ]
  pickblock:
    permission: instabuild.use
    usage: "/pickblock"
    aliases: [ "pb" ]
  instabuildgive:
    permission: instabuild.use
    usage: "/ibg <id:data|material[:data]> [amount]"
    aliases: [ "igive", "ibgive", "ibg", "ig" ]